menu:
  首页: /
  # Archives: /archives
  Github: https://github.com/TIGERB
  Segmentfault: https://segmentfault.com/u/tigerb
  掘金: https://juejin.im/user/5855e82d1b69e6006c9278b4
  # About: /about.html
  # Contact: /contact.html

# Logo Image Source
logo_src: http://cdn.tigerb.cn/20190707142019.png

# Theme Main Subtitle
subtitle_main: <img src="http://cdn.tigerb.cn/20200412182830.png" width="50%">

# Theme Secondary subtitle
susbtitle_secondary: <br>时刻夯实基础，时刻对新技术保持热忱。<br>新一代轻量级「<a href='http://easy-php.tigerb.cn'>EasyPHP</a>」框架作者，「<a href='http://skrshop.tech/'>《电商设计手册 | SkrShop》</a>」作者，「<a href='http://tigerb.cn/go/#/patterns/'>《Go设计模式实战》系列</a>」作者，「<a href='http://tigerb.cn/go/#/kernal/'>《Go语言轻松进阶》系列</a>」作者。

# Footer About Section
about_footer: 新一代轻量级「<a href='http://easy-php.tigerb.cn'>EasyPHP</a>」框架作者，「<a href='http://skrshop.tech/'>《电商设计手册 | SkrShop》</a>」作者，「<a href='http://tigerb.cn/go/#/patterns/'>《Go设计模式实战》系列</a>」作者，「<a href='http://tigerb.cn/go/#/kernal/'>《Go语言轻松进阶》系列</a>」作者。拥有丰富的电商系统开发经验，现于小米集团从事后端研发工作。<br><br><img style="vertical-align:middle" width="30%" src="http://cdn.tigerb.cn/wechat-blog-qrcode.jpg?imageMogr2/thumbnail/260x260!/format/webp/blur/1x0/quality/90|imageslim">

# Default post title
default_post_title: No Code No Life

# Default post cover index page (Recommended)
default_cover_index: "http://cdn.tigerb.cn/20190330161746.jpg?imageMogr2/thumbnail/640x480!/format/webp/blur/1x0/quality/75|imageslim"

# Default post cover index page (Optional)
default_cover_detail: No Code No Life

# Show Dates for posts and pages
show_dates: YYYY-MM-DD

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  # disqus_shortname: TIGERB
  # Facebook comments
  # facebook:
  #   appid:
  #   comment_count: 5
  #   comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/CODERCOOKER
# instagram_url: https://www.instagram.com/codercooker/
github_url: https://github.com/TIGERB
email_url: mailto:tigerbcode@gmail.com
rss_url: \atom.xml
